name: Feature Request
description: Suggest a new Feature for JavaBotBlockAPI
labels: 'Type: Enhancement'
issue_body: false
body:
- type: markdown
  attributes:
    value: |-
      Thank you for taking the time in creating this Feature Request.
      In order to process your feature request as fast and efficiently as possible do we ask you to fill out any required fields (Indicated with a `*`) with the requested information.
- type: checkboxes
  attributes:
    label: Confirmation
    description: Please make sure to have followed these checks.
    options:
      - label: I checked the Issues and Pull request tab for any existing issues or PRs.
        required: true
      - label: My Feature Request is for **JavaBotBlockAPI** and not any external library or BotBlock.org itself.
        required: true
- type: textarea
  attributes:
    label: "Description"
    description: |-
      Give a detailed explanation about your Feature request and why it would be beneficial for JavaBotBlockAPI.
      Just saying "It's cool!" or "I need it" don't count as valid reasons. It needs to have a clear benefit for **other** users too.
  validations:
    required: true
- type: textarea
  attributes:
    label: "Code Example"
    description: |-
      Do you have any Code Snippets that you want to share with us?
      Remember to use Code blocks for smaller snippets and https://paste.gg for larger ones.
    placeholder: |-
      ```java
      public boolean method(){ return true; }
      ```
    render: "java"
- type: textarea
  attributes:
    label: "Additional Information"
    description: "Add any extra info you think is nessesary for this Feature request."
    placeholder: "Put any extra info you like into this field..."
