name: Build Javadocs

on:
  workflow_dispatch:

jobs:
  generateJavadoc:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2.3.4
      with:
        ref: 'master'
    - name: Set up Java 11
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Generate Javadoc
      run: ./gradlew javadoc
    - name: Push changes
      uses: peaceiris/actions-gh-pages@v3.8.0
      with: 
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs
        commit_message: "Update Docs"
        enable_jekyll: true
